local builtin = require('telescope.builtin')
vim.keymap.set('n', '<leader>ff', builtin.find_files, {desc = "[F]ind [F]iles"})
vim.keymap.set('n', '<leader>fg', builtin.live_grep, {desc = "Search in Files"})
vim.keymap.set('n', '<C-p>', builtin.git_files, {desc = "Find Git Files"})
vim.keymap.set('n', '<leader>fb', builtin.buffers, {desc = "Show open buffers"})
